version: 2.1

################# Jobs #########################

jobs:
  prepare-npm-deps:
    executor: default-executor

    steps:
      - checkout

      # Download cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the cache from the same branch
            - v1-dependencies-{{ .Branch }}-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install dependencies
      - run: npm install --no-audit --legacy-peer-deps

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    executor: default-executor

    steps:
      - attach_workspace:
          at: ~/

      - run: npm test


################################################

################# Executors ####################

executors:
  default-executor:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.15

################################################


################# Workflows ####################

workflows:
  version: 2

  commit-workflow:
    jobs:
      - prepare-npm-deps

      - test:
          requires:
            - prepare-npm-deps

################################################
